PKGDIR        ?= ../..
L4DIR         ?= $(PKGDIR)/../../..

TARGET	      := lib4re-util.a lib4re-util.so
SRC_CC        := dataspace_svr.cc name_space_svr.cc goos_fb.cc
PC_FILENAME   := l4re-util
REQUIRES_LIBS := l4re l4re-util-nortti

include $(L4DIR)/mk/lib.mk
